### ISSUE TITLE
Extract "Dominant Color" From Profile Images using "Color Theif"

### ISSUE THREAD

**Issue by nelsonic** [dwyl/stars#18]
see: https://github.com/lokesh/color-thief
demo: http://lokeshdhakar.com/projects/color-thief/

**Comment by nelsonic** [comment]
I'm certainly learning a new class of DOM/DevTools errors:
![image](https://user-images.githubusercontent.com/194400/27259999-3d96e140-5418-11e7-980d-bc4936aa8eb2.png)

🤣

**Comment by nelsonic** [comment]
color identification is kinda poor: 
![image](https://user-images.githubusercontent.com/194400/27260501-7e20570c-5425-11e7-8e8b-9bc3c5d42105.png)

**Comment by nelsonic** [comment]
Color Palette:
![image](https://user-images.githubusercontent.com/194400/27260559-3f11a352-5427-11e7-9e2b-6328a2ff89b5.png)

**Comment by nelsonic** [comment]
It's what we have ...
![image](https://user-images.githubusercontent.com/194400/27260591-fd839570-5427-11e7-86ad-4ea73ce3404a.png)

Let's move on to sorting!

**Comment by nelsonic** [comment]
Profile Images Sorted by main Color:
![image](https://user-images.githubusercontent.com/194400/27261193-d859720c-5435-11e7-94af-7ece9969dc7e.png)

**Comment by nelsonic** [comment]
The page takes a while to load because there are several thousand images ...
![image](https://user-images.githubusercontent.com/194400/27261228-bd729bfc-5436-11e7-9cad-f3dddafa6f09.png)

Firefox is a _lot_ faster than Chrome:
![image](https://user-images.githubusercontent.com/194400/27261237-e813160c-5436-11e7-9ae4-d09b70278248.png)
It's _interesting_ how many people don't bother to update their profile picture...


Anyway, the ***idea*** was to have a "rainbow" of faces... Profile Images _Sorted_ by `main` Color:
![image](https://user-images.githubusercontent.com/194400/27261193-d859720c-5435-11e7-94af-7ece9969dc7e.png)

**Comment by nelsonic** [comment]
Random:
![image](https://user-images.githubusercontent.com/194400/27261393-2384514e-543a-11e7-9602-34a20873e26c.png)

Rainbow:
![image](https://user-images.githubusercontent.com/194400/27261400-3c47e27c-543a-11e7-8574-2b1cebd4fe10.png)

Not spending any more time on this.
`if` anyone `else` wants to try, they are welcome to it! 👍

**Comment by iteles** [comment]
This is all so cool 😍

**Comment by nelsonic** [comment]
@iteles lol! 😆 
I had "_ambitions_" for something _really_ cool.  🦄 
But had to get back to "_real_" work... 😜 
How's _your_ evening going? 🌆 
Still want to _pair_ on that idea...?  💡 
Got 70 mins before leaving for swimming ... 🏊
